name: yuki-bocchi-gateway
services:
  napcat:
    image: mlikiowa/napcat-docker@sha256:644feecdf38b0f0b5e6b4be1271842c3d722a121c0bbfa12ea84feed2bf8deb9
    platform: linux/amd64
    init: true
    restart: unless-stopped
    env_file: .env
    environment:
      ACCOUNT: ${NAPCAT_ACCOUNT:?missing}
      WEBUI_TOKEN: ${NAPCAT_WEBUI_TOKEN:?missing}
      NAPCAT_UID: "0"
      NAPCAT_GID: "0"
      WEBUI_PREFIX: ""
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 127.0.0.1:6099:6099
    volumes:
      - ./data:/app/.config/QQ
      - ./config:/app/napcat/config
      - ./plugins:/app/napcat/plugins
      - ../social-transfer:/yuki-transfer:ro
    stop_grace_period: 30s
