"""Host-owned storage for bounded media generated by plugins."""

from __future__ import annotations

import asyncio
import hashlib
import os
import re
import stat
import uuid
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path

from sqlalchemy import func, select

from qq_ai_bot.persistence.database import Database
from qq_ai_bot.plugin_host.db_models import (
    PluginMediaArtifactModel,
    PluginNotificationOutboxModel,
)
from yuki_plugin_sdk.errors import PluginPermissionError
from yuki_plugin_sdk.models import MediaArtifactHandle

_ALLOWED_MIME = frozenset({"image/png", "image/jpeg", "image/webp", "image/gif"})
_SAFE_FILENAME = re.compile(r"[^A-Za-z0-9._-]+")
_MAX_FILE_BYTES = 5 * 1024 * 1024


@dataclass(frozen=True, slots=True)
class ResolvedMediaArtifact:
    handle_id: str
    plugin_id: str
    content_type: str
    filename: str
    local_path: Path
    byte_size: int
    expires_at: datetime
    sha256: str


class PluginMediaArtifactStore:
    def __init__(self, database: Database, root: Path = Path("data/plugin_artifacts")) -> None:
        self._database = database
        self._root = root.resolve(strict=False)

    async def create(
        self,
        *,
        plugin_id: str,
        data: bytes,
        content_type: str,
        filename: str,
        ttl_seconds: int,
        storage_mb: int,
        expires_at_cap: datetime | None = None,
    ) -> MediaArtifactHandle:
        mime = content_type.strip().casefold()
        if mime not in _ALLOWED_MIME or not _matches_mime(data, mime):
            raise ValueError("unsupported or mismatched media type")
        if not data or len(data) > _MAX_FILE_BYTES:
            raise ValueError("media artifact must contain 1 byte to 5 MiB")
        if not 60 <= ttl_seconds <= 7 * 86_400:
            raise ValueError("media artifact TTL must be between 60 seconds and 7 days")
        safe_name = _filename(filename, mime)
        capacity = storage_mb * 1024 * 1024
        async with self._database.sessions() as session:
            used = int(
                await session.scalar(
                    select(func.coalesce(func.sum(PluginMediaArtifactModel.byte_size), 0)).where(
                        PluginMediaArtifactModel.plugin_id == plugin_id
                    )
                )
                or 0
            )
        if used + len(data) > capacity:
            raise PluginPermissionError("plugin media storage quota exceeded")
        now = datetime.now(UTC)
        expires_at = now + timedelta(seconds=ttl_seconds)
        if expires_at_cap is not None:
            expires_at = min(expires_at, _aware(expires_at_cap))
        if expires_at <= now:
            raise PluginPermissionError("media artifact has already expired")
        digest = hashlib.sha256(data).hexdigest()
        handle_id = uuid.uuid4().hex
        directory = self._root / _plugin_directory(plugin_id)
        destination = directory / f"{handle_id}-{safe_name}"
        await asyncio.to_thread(_atomic_write, directory, destination, data)
        try:
            async with self._database.sessions() as session, session.begin():
                session.add(
                    PluginMediaArtifactModel(
                        handle_id=handle_id,
                        plugin_id=plugin_id,
                        content_type=mime,
                        filename=safe_name,
                        byte_size=len(data),
                        sha256=digest,
                        storage_path=str(destination),
                        created_at=now,
                        expires_at=expires_at,
                    )
                )
        except Exception:
            await asyncio.to_thread(destination.unlink, missing_ok=True)
            raise
        return MediaArtifactHandle(
            handle_id=handle_id,
            content_type=mime,
            filename=safe_name,
            byte_size=len(data),
            sha256=digest,
            expires_at=expires_at,
        )

    async def resolve(self, *, plugin_id: str, handle_id: str) -> ResolvedMediaArtifact:
        async with self._database.sessions() as session:
            row = await session.get(PluginMediaArtifactModel, handle_id)
        if row is None or row.plugin_id != plugin_id or _aware(row.expires_at) <= datetime.now(UTC):
            raise PluginPermissionError("media artifact is missing, expired, or foreign")
        path, expected_root, available = await asyncio.to_thread(
            _resolve_artifact_path,
            row.storage_path,
            self._root / _plugin_directory(plugin_id),
        )
        if not path.is_relative_to(expected_root) or not available:
            raise PluginPermissionError("media artifact storage is unavailable")
        return ResolvedMediaArtifact(
            handle_id=row.handle_id,
            plugin_id=row.plugin_id,
            content_type=row.content_type,
            filename=row.filename,
            local_path=path,
            byte_size=row.byte_size,
            expires_at=row.expires_at,
            sha256=row.sha256,
        )

    async def read_owned(
        self, *, plugin_id: str, handle_id: str
    ) -> tuple[ResolvedMediaArtifact, bytes]:
        """Read one explicitly returned owned handle, bounded and version checked."""
        resolved = await self.resolve(plugin_id=plugin_id, handle_id=handle_id)
        data = await asyncio.to_thread(_read_verified, resolved)
        current = await self.resolve(plugin_id=plugin_id, handle_id=handle_id)
        if current != resolved:
            raise PluginPermissionError("media artifact changed during reading")
        return resolved, data

    async def cleanup(self) -> int:
        now = datetime.now(UTC)
        async with self._database.sessions() as session, session.begin():
            rows = (
                await session.scalars(
                    select(PluginMediaArtifactModel).where(
                        PluginMediaArtifactModel.expires_at <= now,
                        ~PluginMediaArtifactModel.handle_id.in_(
                            select(PluginNotificationOutboxModel.media_handle_id).where(
                                PluginNotificationOutboxModel.media_handle_id.is_not(None),
                                PluginNotificationOutboxModel.status.in_(("pending", "processing")),
                            )
                        ),
                    )
                )
            ).all()
            paths = [Path(row.storage_path) for row in rows]
            for row in rows:
                await session.delete(row)
        for path in paths:
            await asyncio.to_thread(path.unlink, missing_ok=True)
        return len(paths)


def _matches_mime(data: bytes, mime: str) -> bool:
    if mime == "image/png":
        return data.startswith(b"\x89PNG\r\n\x1a\n")
    if mime == "image/jpeg":
        return data.startswith(b"\xff\xd8\xff")
    if mime == "image/gif":
        return data.startswith((b"GIF87a", b"GIF89a"))
    if mime == "image/webp":
        return len(data) >= 12 and data[:4] == b"RIFF" and data[8:12] == b"WEBP"
    return False


def _filename(value: str, mime: str) -> str:
    candidate = Path(value.strip()).name
    safe = _SAFE_FILENAME.sub("_", candidate).strip("._")[:180]
    suffix = {
        "image/png": ".png",
        "image/jpeg": ".jpg",
        "image/webp": ".webp",
        "image/gif": ".gif",
    }[mime]
    if not safe:
        safe = f"artifact{suffix}"
    elif not safe.casefold().endswith(suffix):
        safe += suffix
    return safe


def _plugin_directory(plugin_id: str) -> str:
    return hashlib.sha256(plugin_id.encode()).hexdigest()[:32]


def _atomic_write(directory: Path, destination: Path, data: bytes) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    temporary = directory / f".{destination.name}.{uuid.uuid4().hex}.tmp"
    try:
        temporary.write_bytes(data)
        os.replace(temporary, destination)
    finally:
        temporary.unlink(missing_ok=True)


def _resolve_artifact_path(value: str, expected_root: Path) -> tuple[Path, Path, bool]:
    path = Path(value).resolve(strict=False)
    root = expected_root.resolve(strict=False)
    return path, root, path.is_file()


def _aware(value: datetime) -> datetime:
    return value.replace(tzinfo=UTC) if value.tzinfo is None else value.astimezone(UTC)


def _read_verified(item: ResolvedMediaArtifact) -> bytes:
    descriptor = os.open(item.local_path, os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0))
    with os.fdopen(descriptor, "rb") as stream:
        info = os.fstat(stream.fileno())
        if not stat.S_ISREG(info.st_mode) or info.st_size != item.byte_size:
            raise PluginPermissionError("media artifact storage version changed")
        if not 0 < info.st_size <= _MAX_FILE_BYTES:
            raise PluginPermissionError("media artifact exceeds read budget")
        data = stream.read(_MAX_FILE_BYTES + 1)
    if len(data) != item.byte_size or hashlib.sha256(data).hexdigest() != item.sha256:
        raise PluginPermissionError("media artifact content version changed")
    return data
